import { Sparkles } from 'lucide-react'

export default function AiDocNotice() {
  return (
    <span
      className="inline-flex items-center gap-1.5 font-mono text-[11px] text-muted border border-border rounded-full px-3 py-1 tracking-wide shrink-0"
      title="Generated by Claude Code from the project codebase — not hand-written."
    >
      <Sparkles size={11} className="shrink-0" />
      <span className="hidden sm:inline">AI-generated docs</span>
    </span>
  )
}
